export enum Permission {
  ROLE_CREATE = 'role:create',
  ROLE_READ = 'role:read',
  ROLE_UPDATE = 'role:update',
  ROLE_DELETE = 'role:delete',
  ROLE_ASSIGN = 'role:assign',
  ROLE_REVOKE = 'role:revoke',
  COMPANY_CREATE = 'company:create',
  COMPANY_READ = 'company:read',
  COMPANY_UPDATE = 'company:update',
  COMPANY_DELETE = 'company:delete',
  USER_CREATE = 'user:create',
  USER_READ = 'user:read',
  USER_UPDATE = 'user:update',
  USER_DELETE = 'user:delete',
  USER_DELEGATE = 'user:delegate',
  PARAMETERS_UPDATE = 'parameters:update',
  CONTRACT_CREATE = 'contract:create',
  CONTRACT_READ = 'contract:read',
  CONTRACT_UPDATE = 'contract:update',
  CONTRACT_DELETE = 'contract:delete',
  REPORTS_CREATE = 'reports:create',
  REPORTS_READ = 'reports:read',
  REPORTS_UPDATE = 'reports:update',
  REPORTS_DELETE = 'reports:delete',
  REPORTS_APPROVE = 'reports:approve',
}
